extension_dir = "/tmp/php_install/usr/lib/php/20220829/"
extension = pdo.so
extension = pdo_sqlite.so
extension = pdo_mysql.so
extension = sqlite3.so
extension = mysqli.so
extension = opcache.so
extension = readline.so
memory_limit = 256M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
